### ISSUE TITLE
Allow one or multiple alarms for a chore

### ISSUE THREAD

**Issue by andreoliwa** [andreoliwa/python-dontforget#11]
As a forgetful person, I want to receive different early warnings for different bills, a specified number of days before their due dates, so I can pay attention to those I forget more.

Example: my cable TV's due date is on day 10, I'd like to be warned by e-mail 2 days before.
But, for my vehicle tax, I'd like to be warned 5 days before, cause I regularly forget to pay this one.

---

[number] [day type]
Examples of "before" reminders: 1 day, 2 weekdays, 1 weekend, 1 Thursday, every 2 days, every hour, every 15 minutes

The reminders should keep going until the task is marked as done or skipped

**Comment by andreoliw** [comment]
As a forgetful person, I want to receive different early warnings for different bills, a specified number of days before their due dates, so I can pay attention to those I forget more.

Example: my cable TV's due date is on day 10, I'd like to be warned by e-mail 2 days before.
But, for my vehicle tax, I'd like to be warned 5 days before, cause I regularly forget to pay this one.

**Comment by andreoliwa** [comment]
This issue has become obsolete. See #135.
